gp1:
  conf: data1_env1
  im:
    - check_delegate_1

gp2:
  conf: data2_env2
  im:
    - check_delegate_2

gp3:
  conf: data1_env1
  im:
    - check_delegate_1

gp4:
  conf: data2_env2
  im:
    - check_delegate_2

gp_rules:

  conf: data2_env2

  ir:
    - "package *= data"

  er:
    - "module !*= excel"


    