simple_stage_1:
  include:
    - gp1
    - gp2

simple_stage_2:
  include:
    - gp3
    - gp4

threaded_stage_1:
  threads: 2
  include:
    - gp1
    - gp2

threaded_stage_2:
  threads: 2
  include:
    - gp3
    - gp4